package com.example.ETBPlatform.enity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "users")
@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    @Id   //why not autogenerated ? bcz this id is coming from keycloak
    @Column(name = "id" , updatable = false , nullable = false)
    private UUID id;

    @Column(name = "name" , nullable = false)
    private String name;

    @Column(name = "email" , nullable = false)
    private String email;

    //organized event
    @OneToMany(mappedBy = "organizer" ,  cascade = CascadeType.ALL)
    private List<Event> organizedEvents = new ArrayList<>();

    //attending events
    @ManyToMany
    @JoinTable(
            name = "user_attending_events" ,
            joinColumns = @JoinColumn(name ="user_id"),
            inverseJoinColumns = @JoinColumn(name = "event_id")
    )
    private List<Event>attendingEvents = new ArrayList<>();

    //staffing events
    @ManyToMany
    @JoinTable(
            name="staff_attending_events" ,
            joinColumns = @JoinColumn(name = "user_id") ,
            inverseJoinColumns = @JoinColumn(name = "event_id")
    )
    private List<Event> staffingEvents = new ArrayList<>();

    @CreatedDate
    @Column(name = "created_at" , updatable = false , nullable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at" , updatable = false , nullable = false)
    private LocalDateTime updatedAt;



}
