spring.application.name=ETBPlatform
spring.datasource.url=jdbc:postgresql://localhost:5432/ETB_db
spring.datasource.username = postgres
 spring.datasource.password = 010823
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resource.jwt.issuer-url=http://localhost:9090/realms/event-ticket-platform